# Generated by Django 2.1.7 on 2019-04-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('sex', models.CharField(choices=[('mail', '男'), ('femail', '女')], default='女', max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
