# Generated by Django 2.1.7 on 2019-06-25 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0002_auto_20190625_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
