# Generated by Django 2.1.7 on 2019-06-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0003_auto_20190625_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sex',
            new_name='gender',
        ),
    ]
