# Generated by Django 2.1.7 on 2019-08-08 07:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=20)),
                ('gender', models.CharField(default='女', max_length=2)),
                ('birthday', models.DateField(default=datetime.date(2019, 8, 8))),
            ],
        ),
        migrations.CreateModel(
            name='UserSkin',
            fields=[
                ('uid', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('stime', models.DateTimeField(default=datetime.datetime(2019, 8, 8, 7, 19, 35, 296944, tzinfo=utc))),
                ('totalScore', models.IntegerField(default=100)),
                ('youngScore', models.IntegerField(default=100)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Face.UserInfo')),
            ],
        ),
    ]
