# Generated by Django 2.1.7 on 2019-08-08 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskin',
            name='stime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 7, 27, 9, 809051, tzinfo=utc)),
        ),
    ]
