# Generated by Django 2.1.7 on 2019-08-08 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0002_auto_20190808_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 8, 8, 12, 43, 26, 999057, tzinfo=utc))),
                ('image', models.BinaryField()),
            ],
            options={
                'db_table': 'ImageRecord',
            },
        ),
        migrations.CreateModel(
            name='SkinRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 8, 8, 12, 43, 26, 998203, tzinfo=utc))),
                ('age', models.IntegerField()),
                ('wrinkleCount', models.IntegerField()),
                ('wrinkleScore', models.IntegerField()),
                ('wrinkleGlabellaCount', models.IntegerField()),
                ('wrinkleCrowfeetCount', models.IntegerField()),
                ('wrinkleNasolabialCount', models.IntegerField()),
                ('wrinkleEyecornerCount', models.IntegerField()),
                ('wrinkleForeheadCount', models.IntegerField()),
                ('pockmarkCount', models.IntegerField()),
                ('pockmarkScore', models.IntegerField()),
                ('blackheadCount', models.IntegerField()),
                ('blackheadScore', models.IntegerField()),
                ('darkCircleResult', models.FloatField()),
                ('colorResult', models.CharField(max_length=16)),
                ('skinTypeOily', models.CharField(max_length=16)),
                ('skinTypeDry', models.CharField(max_length=16)),
                ('skinTypeMixed', models.CharField(max_length=16)),
                ('foreheadOilResult', models.FloatField()),
                ('foreheadChinResult', models.FloatField()),
                ('foreheadLeftCheekResult', models.FloatField()),
                ('foreheadRightCheekResult', models.FloatField()),
                ('moistureResult', models.CharField(max_length=32)),
                ('moistureScore', models.IntegerField()),
                ('roughnessScore', models.IntegerField()),
                ('poreCount', models.IntegerField()),
                ('poreScore', models.IntegerField()),
            ],
            options={
                'db_table': 'SkinRecord',
            },
        ),
        migrations.CreateModel(
            name='UserFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11)),
                ('ftime', models.DateTimeField(default=datetime.datetime(2019, 8, 8, 12, 43, 26, 997668, tzinfo=utc))),
                ('faceShape', models.CharField(max_length=16)),
                ('lipShape', models.CharField(max_length=16)),
                ('chinShape', models.CharField(max_length=16)),
                ('eyeShape', models.CharField(max_length=16)),
                ('browShape', models.CharField(max_length=16)),
                ('noseShape', models.CharField(max_length=16)),
                ('forehead', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'UserFace',
            },
        ),
        migrations.RemoveField(
            model_name='userskin',
            name='userinfo',
        ),
        migrations.AddField(
            model_name='userskin',
            name='healthScore',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userskin',
            name='oilScore',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userskin',
            name='softScore',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userskin',
            name='stime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 12, 43, 26, 997227, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='UserInfo',
        ),
        migrations.AlterModelTable(
            name='userskin',
            table='UserSkin',
        ),
    ]
