# Generated by Django 2.1.7 on 2019-08-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0003_auto_20190808_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageRecord',
        ),
        migrations.DeleteModel(
            name='SkinRecord',
        ),
        migrations.DeleteModel(
            name='UserFace',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.DeleteModel(
            name='UserSkin',
        ),
    ]
