# Generated by Django 2.1.7 on 2019-08-08 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Face', '0004_auto_20190808_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 8, 8, 16, 5, 49, 842833, tzinfo=utc))),
                ('image', models.BinaryField()),
            ],
            options={
                'db_table': 'ImageRecord',
            },
        ),
        migrations.CreateModel(
            name='SkinRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 8, 8, 16, 5, 49, 841985, tzinfo=utc))),
                ('age', models.IntegerField()),
                ('wrinkleCount', models.IntegerField()),
                ('wrinkleScore', models.IntegerField()),
                ('wrinkleGlabellaCount', models.IntegerField()),
                ('wrinkleCrowfeetCount', models.IntegerField()),
                ('wrinkleNasolabialCount', models.IntegerField()),
                ('wrinkleEyecornerCount', models.IntegerField()),
                ('wrinkleForeheadCount', models.IntegerField()),
                ('pockmarkCount', models.IntegerField()),
                ('pockmarkScore', models.IntegerField()),
                ('blackheadCount', models.IntegerField()),
                ('blackheadScore', models.IntegerField()),
                ('darkCircleResult', models.FloatField()),
                ('colorResult', models.CharField(max_length=16)),
                ('skinTypeOily', models.CharField(max_length=16)),
                ('skinTypeDry', models.CharField(max_length=16)),
                ('skinTypeMixed', models.CharField(max_length=16)),
                ('foreheadOilResult', models.FloatField()),
                ('foreheadChinResult', models.FloatField()),
                ('foreheadLeftCheekResult', models.FloatField()),
                ('foreheadRightCheekResult', models.FloatField()),
                ('moistureResult', models.CharField(max_length=32)),
                ('moistureScore', models.IntegerField()),
                ('roughnessScore', models.IntegerField()),
                ('poreCount', models.IntegerField()),
                ('poreScore', models.IntegerField()),
            ],
            options={
                'db_table': 'SkinRecord',
            },
        ),
        migrations.CreateModel(
            name='UserFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11)),
                ('ftime', models.DateTimeField(default=datetime.datetime(2019, 8, 8, 16, 5, 49, 841492, tzinfo=utc))),
                ('faceShape', models.CharField(max_length=16)),
                ('lipShape', models.CharField(max_length=16)),
                ('chinShape', models.CharField(max_length=16)),
                ('eyeShape', models.CharField(max_length=16)),
                ('browShape', models.CharField(max_length=16)),
                ('noseShape', models.CharField(max_length=16)),
                ('forehead', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'UserFace',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=20)),
                ('gender', models.CharField(default='女', max_length=2)),
                ('birthday', models.DateField(default=datetime.date(2019, 8, 8))),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='UserSkin',
            fields=[
                ('uid', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('stime', models.DateTimeField(default=datetime.datetime(2019, 8, 8, 16, 5, 49, 841049, tzinfo=utc))),
                ('totalScore', models.IntegerField(default=100)),
                ('youngScore', models.IntegerField(default=100)),
                ('healthScore', models.IntegerField(default=100)),
                ('oilScore', models.IntegerField(default=100)),
                ('softScore', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'UserSkin',
            },
        ),
    ]
