# Generated by Django 2.1.7 on 2019-08-09 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0006_auto_20190809_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 1, 5, 24, 242177, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='skinrecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 1, 5, 24, 241430, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userface',
            name='ftime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 1, 5, 24, 240935, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uid',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userskin',
            name='stime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 1, 5, 24, 240541, tzinfo=utc)),
        ),
    ]
