# Generated by Django 2.1.7 on 2019-08-09 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0007_auto_20190809_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 31, 4, 454298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='skinrecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 31, 4, 453552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userface',
            name='ftime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 31, 4, 453106, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userskin',
            name='stime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 6, 31, 4, 452592, tzinfo=utc)),
        ),
    ]
